import { Browser } from "../../browser";
import { crawlGlassdoor } from "./crawlGlassdoor";


class extractGlassdoor {
    constructor() { }

    async execute() : Promise<Object[]> {
        const data = [];

        const glassdoor = new crawlGlassdoor();
        const list = []
        list.push({"company":"180 Seguros","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-180-Seguros-EI_IE6397601.13,24.htm"})
        list.push({"company":"Addi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-ADDI-EI_IE3843870.13,17.htm"})
        list.push({"company":"99","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-99-EI_IE1384588.13,15.htm"})
        list.push({"company":"Adyen","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Adyen-EI_IE684495.13,18.htm"})
        list.push({"company":"Agi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Agi-EI_IE1997188.13,16.htm"})
        // list.push({"company":"Alelo Brasil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Alelo-EI_IE502801.13,18.htm"})
        // list.push({"company":"Alice","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Alice-EI_IE4315940.13,18.htm"})
        // list.push({"company":"alt.bank","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Alt-Bank-EI_IE2961448.13,21.htm"})
        // list.push({"company":"Alura","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Alura-EI_IE2500530.13,18.htm"})
        // list.push({"company":"Amazon","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Amazon-EI_IE6036.13,19.htm"})
        // list.push({"company":"Ame Digital","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Ame-Digital-EI_IE2860094.13,24.htm"})
        // list.push({"company":"Apple","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Apple-EI_IE1138.13,18.htm"})
        // list.push({"company":"Atlassian","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Atlassian-EI_IE115699.13,22.htm"})
        // list.push({"company":"Auth0","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Auth0-EI_IE1162798.13,18.htm"})
        // list.push({"company":"Avanade","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Avanade-EI_IE11701.13,20.htm"})
        // list.push({"company":"Avenue Code","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Avenue-Code-EI_IE456173.13,24.htm"})
        // list.push({"company":"AWS","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Amazon-EI_IE6036.13,19.htm"})
        // list.push({"company":"B2W Digital","url":"https://www.glassdoor.com.br/Overview/Working-at-americanas-s-a-EI_IE10939.11,25.htm?countryRedirect=true"})
        // list.push({"company":"B2W Market Place","url":"https://www.glassdoor.com.br/Overview/Working-at-americanas-s-a-EI_IE10939.11,25.htm?countryRedirect=true"})
        // list.push({"company":"Backbase","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Backbase-EI_IE117266.13,21.htm"})
        // list.push({"company":"BairesDev","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-BairesDev-EI_IE864485.13,22.htm"})
        // list.push({"company":"Banco BV","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-banco-BV-EI_IE333951.13,21.htm"})
        // list.push({"company":"Banco Inter","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Inter-EI_IE2483031.13,18.htm"})
        // list.push({"company":"Banco Next","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Banco-Next-EI_IE4839127.13,23.htm"})
        // list.push({"company":"Banco Original","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Banco-Original-EI_IE1026577.13,27.htm"})
        // list.push({"company":"Banco Pan","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Banco-PAN-EI_IE1184444.13,22.htm"})
        // list.push({"company":"BanQi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-banQi-EI_IE4266216.13,18.htm"})
        // list.push({"company":"Beep Saúde","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Beep-Sa%C3%BAde-EI_IE2836017.13,23.htm"})
        // list.push({"company":"Belvo","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Belvo-EI_IE3275125.13,18.htm"})
        // list.push({"company":"Bitso","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Bitso-EI_IE1710750.13,18.htm"})
        // list.push({"company":"Booking.com","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Booking-com-EI_IE256653.13,24.htm"})
        // list.push({"company":"BossaBox","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-BossaBox-EI_IE2800036.13,21.htm"})
        // list.push({"company":"Grupo Boticário","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Grupo-Botic%C3%A1rio-EI_IE2195061.13,28.htm"})
        // list.push({"company":"Banco Bradesco","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Banco-Bradesco-EI_IE10997.13,27.htm"})
        // list.push({"company":"BTG Pactual","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-BTG-Pactual-EI_IE411540.13,24.htm"})
        // list.push({"company":"Buser Brasil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Buser-EI_IE2844045.13,18.htm"})
        // list.push({"company":"Bytedance","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-ByteDance-EI_IE1624196.13,22.htm"})
        // list.push({"company":"C6 Bank","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-C6-Bank-EI_IE2469864.13,20.htm"})
        // list.push({"company":"CI&T","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-CI-and-T-EI_IE140265.13,21.htm"})
        // list.push({"company":"ClickBus","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-ClickBus-EI_IE955083.13,21.htm"})
        // list.push({"company":"Conta Azul","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-ContaAzul-EI_IE1066463.13,22.htm"})
        // list.push({"company":"Contabilizei","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-ContaAzul-EI_IE1066463.13,22.htm"})
        // list.push({"company":"Cora","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Cora-Bank-EI_IE3078822.13,22.htm"})
        // list.push({"company":"Cornershop by Uber","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Cornershop-by-Uber-EI_IE2435147.13,31.htm"})
        // list.push({"company":"Creditas","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Creditas-EI_IE2122901.13,21.htm"})
        // list.push({"company":"Cubos Tecnologia","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Cubos-EI_IE2110357.13,18.htm"})
        // list.push({"company":"Dafiti","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Dafiti-EI_IE701830.13,19.htm"})
        // list.push({"company":"Dell","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Dell-Technologies-EI_IE1327.13,30.htm"})
        // list.push({"company":"DocuSign","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-DocuSign-EI_IE307604.13,21.htm"})
        // list.push({"company":"EBANX","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-EBANX-EI_IE1105630.13,18.htm"})
        // list.push({"company":"Elo7","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Elo7-EI_IE864738.13,17.htm"})
        // list.push({"company":"Escale","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Escale-EI_IE2255850.13,19.htm"})
        // list.push({"company":"Expedia Group (Open Source)","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Expedia-Group-EI_IE9876.13,26.htm"})
        // list.push({"company":"Expedia Inc","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Expedia-Group-EI_IE9876.13,26.htm"})
        // list.push({"company":"Expedia Dot Com","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Expedia-Group-EI_IE9876.13,26.htm"})
        // list.push({"company":"Facebook","url":"https://www.glassdoor.com.br/metacareers"})
        // list.push({"company":"Farfetch","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-FARFETCH-EI_IE799159.13,21.htm"})
        // list.push({"company":"FinanZero","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-FinanZero-EI_IE2812408.13,22.htm"})
        // list.push({"company":"Franq Openbank","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Franq-Openbank-EI_IE4022440.13,27.htm"})
        // list.push({"company":"Frubana","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Frubana-EI_IE2462202.13,20.htm"})
        // list.push({"company":"GetNinjas","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-GetNinjas-EI_IE1493964.13,22.htm"})
        // list.push({"company":"GFT Group","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-GFT-Group-EI_IE5353645.13,22.htm"})
        // list.push({"company":"Globant","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Globant-EI_IE150678.13,20.htm"})
        // list.push({"company":"Globo","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Globo-EI_IE321393.13,18.htm"})
        // list.push({"company":"Google","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Google-EI_IE9079.13,19.htm"})
        // list.push({"company":"GuiaBolso","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Guiabolso-EI_IE1268911.13,22.htm"})
        // list.push({"company":"Guru Investimentos","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Guru-EI_IE4570065.13,17.htm"})
        // list.push({"company":"Gympass","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Gympass-EI_IE1419026.13,20.htm"})
        // list.push({"company":"Hash","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Hash-EI_IE3133159.13,17.htm"})
        // list.push({"company":"HelloFresh","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-HelloFresh-EI_IE998728.13,23.htm"})
        // list.push({"company":"Hotmart","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Hotmart-EI_IE1139514.13,20.htm"})
        // list.push({"company":"Huge","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Huge-EI_IE139928.13,17.htm"})
        // list.push({"company":"Hurb","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Hurb-EI_IE936163.13,17.htm"})
        // list.push({"company":"idwall","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-idwall-EI_IE1948154.13,19.htm"})
        // list.push({"company":"iFood","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-iFood-EI_IE1396166.13,18.htm"})
        // list.push({"company":"ília","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-%C3%ADlia-Brazil-EI_IE4266621.13,24.htm"})
        // list.push({"company":"Intuit","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Intuit-EI_IE2293.13,19.htm"})
        // list.push({"company":"Invillia","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Invillia-EI_IE2411180.13,21.htm"})
        // list.push({"company":"isaac","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-isaac-Brazil-EI_IE4496925.13,25.htm"})
        // list.push({"company":"Itaú: Itaú + Itaú Unibanco","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Ita%C3%BA-Unibanco-Ita%C3%BA-BBA-e-Rede-EI_IE10999.13,42.htm"})
        // list.push({"company":"Itaú: iti Itaú","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-iti-Ita%C3%BA-EI_IE3347026.13,21.htm"})
        // list.push({"company":"James Delivery","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-James-Delivery-EI_IE2570636.13,27.htm"})
        // list.push({"company":"John Deere","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-John-Deere-EI_IE195.13,23.htm"})
        // list.push({"company":"Jusbrasil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Jusbrasil-EI_IE755082.13,22.htm"})
        // list.push({"company":"Kavak","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Kavak-EI_IE2833457.13,18.htm"})
        // list.push({"company":"Kovi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Kovi-Tecnologia-EI_IE2928151.13,28.htm"})
        // list.push({"company":"Linx","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Linx-EI_IE676478.13,17.htm"})
        // list.push({"company":"Liv Up","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Liv-Up-EI_IE2319967.13,19.htm"})
        // list.push({"company":"Locaweb","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Locaweb-EI_IE336159.13,20.htm"})
        // list.push({"company":"Loft","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Loft-EI_IE2845308.13,17.htm"})
        // list.push({"company":"Loggi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Loggi-EI_IE1912134.13,18.htm"})
        // list.push({"company":"Luizalabs","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Luizalabs-EI_IE2484356.13,22.htm"})
        // list.push({"company":"M4U","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-M4U-EI_IE721446.13,16.htm"})
        // list.push({"company":"MadeiraMadeira","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-M4U-EI_IE721446.13,16.htm"})
        // list.push({"company":"MaxMilhas","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-MaxMilhas-EI_IE1973935.13,22.htm"})
        // list.push({"company":"Medallia","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Medallia-EI_IE268806.13,21.htm"})
        // list.push({"company":"Méliuz","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-M%C3%A9liuz-EI_IE1384857.13,19.htm"})
        // list.push({"company":"Memed","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Memed-EI_IE2491775.13,18.htm"})
        // list.push({"company":"Mercado Libre","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Mercado-Livre-EI_IE2372230.13,26.htm"})
        // list.push({"company":"Mercado Livre","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Mercado-Livre-EI_IE2372230.13,26.htm"})
        // list.push({"company":"meutudo.","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Meu-Tudo-EI_IE2842333.13,21.htm"})
        // list.push({"company":"Movile","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Movile-EI_IE301687.13,19.htm"})
        // list.push({"company":"N26","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-N26-EI_IE1032903.13,16.htm"})
        // list.push({"company":"N26 Brazil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-N26-EI_IE1032903.13,16.htm"})
        // list.push({"company":"Neon","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Neon-Pagamentos-EI_IE2342778.13,28.htm"})
        // list.push({"company":"Netflix","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Netflix-EI_IE11891.13,20.htm"})
        // list.push({"company":"Nexoos","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Nexoos-EI_IE1646586.13,19.htm"})
        // list.push({"company":"NoVerde","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Noverde-EI_IE2128189.13,20.htm"})
        // list.push({"company":"Olist","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Olist-EI_IE2315236.13,18.htm"})
        // list.push({"company":"OLX Brasil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-OLX-Brasil-EI_IE2500798.13,23.htm"})
        // list.push({"company":"Open Co","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Open-Co-EI_IE4806570.13,20.htm"})
        // list.push({"company":"Pagar.me","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Pagar-me-EI_IE1341379.13,21.htm"})
        // list.push({"company":"PagSeguro","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PagBank-PagSeguro-EI_IE1335500.13,30.htm"})
        // list.push({"company":"Pagbank","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PagBank-PagSeguro-EI_IE1335500.13,30.htm"})
        // list.push({"company":"PayPal","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PayPal-EI_IE9848.13,19.htm"})
        // list.push({"company":"PayU","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PayU-EI_IE1018226.13,17.htm"})
        // list.push({"company":"PedidosYa","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PedidosYa-EI_IE1275051.13,22.htm"})
        // list.push({"company":"PicPay","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-PicPay-EI_IE2020252.13,19.htm"})
        // list.push({"company":"Pipefy","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Pipefy-EI_IE1469776.13,19.htm"})
        // list.push({"company":"Pipo Saúde","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Pipo-Sa%C3%BAde-EI_IE3504342.13,23.htm"})
        // list.push({"company":"Pismo","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Pismo-EI_IE2744250.13,18.htm"})
        // list.push({"company":"Platzi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Platzi-EI_IE1485738.13,19.htm"})
        // list.push({"company":"QuintoAndar","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-QuintoAndar-EI_IE1161693.13,24.htm"})
        // list.push({"company":"Rappi","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Rappi-EI_IE1275894.13,18.htm"})
        // list.push({"company":"RD Station","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-RD-Station-EI_IE965847.13,23.htm"})
        // list.push({"company":"RecargaPay","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-RecargaPay-EI_IE1397947.13,23.htm"})
        // list.push({"company":"Red Hat","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Red-Hat-EI_IE8868.13,20.htm"})
        // list.push({"company":"Remessa Online","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Remessa-Online-EI_IE2125029.13,27.htm"})
        // list.push({"company":"Revolut","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Revolut-EI_IE1176471.13,20.htm"})
        // list.push({"company":"Safra","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Banco-Safra-EI_IE15189.13,24.htm"})
        // list.push({"company":"Sami","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Sami-Sa%C3%BAde-EI_IE3577625.13,23.htm"})
        // list.push({"company":"Sanar","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Sanar-EI_IE2313421.13,18.htm"})
        // list.push({"company":"Santander Brasil","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Santander-EI_IE828048.13,22.htm"})
        // list.push({"company":"Serasa Experian","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Serasa-EI_IE2469855.13,19.htm"})
        // list.push({"company":"Shopee","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Shopee-EI_IE1263091.13,19.htm"})
        // list.push({"company":"Softplan","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Softplan-EI_IE656864.13,21.htm"})
        // list.push({"company":"Stone","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Stone-EI_IE1093539.13,18.htm"})
        // list.push({"company":"Stripe","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Stripe-EI_IE671932.13,19.htm"})
        // list.push({"company":"SumUp","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-SumUp-EI_IE673829.13,18.htm"})
        // list.push({"company":"Sympla","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Sympla-EI_IE1622849.13,19.htm"})
        // list.push({"company":"Take Blip","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Take-Blip-EI_IE754538.13,22.htm"})
        // list.push({"company":"ThoughtWorks","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Thoughtworks-EI_IE38334.13,25.htm"})
        // list.push({"company":"Toptal","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Toptal-EI_IE882070.13,19.htm"})
        // list.push({"company":"TOTVS","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-TOTVS-EI_IE140298.13,18.htm"})
        // list.push({"company":"Trustly","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Trustly-EI_IE962720.13,20.htm"})
        // list.push({"company":"Trybe","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Trybe-Brazil-EI_IE3790463.13,25.htm"})
        // list.push({"company":"Uber","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Uber-EI_IE575263.13,17.htm"})
        // list.push({"company":"Compass.uol","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Compass-Uol-EI_IE1331935.13,24.htm"})
        // list.push({"company":"Via","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Via-EI_IE2002288.13,16.htm"})
        // list.push({"company":"VTEX","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-VTEX-EI_IE713645.13,17.htm"})
        // list.push({"company":"Warren","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Warren-EI_IE2233093.13,19.htm"})
        // list.push({"company":"WeWork","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-WeWork-EI_IE661275.13,19.htm"})
        // list.push({"company":"Wildlife Studios","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Wildlife-Studios-EI_IE1192101.13,29.htm"})
        // list.push({"company":"will bank","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-will-bank-EI_IE4209911.13,22.htm"})
        // list.push({"company":"Xerpa","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Betterfly-EI_IE4344332.13,22.htm"})
        // list.push({"company":"Youse","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Youse-Seguros-EI_IE1273564.13,26.htm"})
        // list.push({"company":"Zé Delivery","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Z%C3%A9-Delivery-EI_IE3219952.13,24.htm"})
        // list.push({"company":"Zendesk","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Zendesk-EI_IE360923.13,20.htm"})
        // list.push({"company":"Zenklub","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Zenklub-EI_IE3336218.13,20.htm"})
        // list.push({"company":"Zenvia","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Zenvia-EI_IE1290025.13,19.htm"})
        // list.push({"company":"Zoop","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Zoop-EI_IE2850162.13,17.htm"})
        // list.push({"company":"Zup Innovation","url":"https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Zup-Innovation-EI_IE2482761.13,27.htm"})
        // // Unicorns
        // list.push({ "company": "Mercado Bitcoin", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Mercado-Bitcoin-EI_IE2748106.13,28.htm" },)
        // list.push({ "company": "cloudwalk", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-CloudWalk-Inc-EI_IE2722308.13,26.htm" },)
        // list.push({ "company": "tembici", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Tembici-EI_IE2486348.13,20.htm" },)
        // list.push({ "company": "Intelipost", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Intelipost-EI_IE2484852.13,23.htm" },)
        // list.push({ "company": "Ingresse", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Ingresse-EI_IE2384355.13,21.htm" },)
        // list.push({ "company": "Swap", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Swap-Brazil-EI_IE4742954.13,24.htm" },)
        // list.push({ "company": "EmCasa", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-EmCasa-Brazil-EI_IE2828637.13,26.htm" },)
        // list.push({ "company": "Rocketchat", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Rocket-Chat-EI_IE2244250.13,24.htm" },)
        // list.push({ "company": "Omie", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Omie-EI_IE2483805.13,17.htm" },)
        // list.push({ "company": "Cobli", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Cobli-EI_IE2304948.13,18.htm" },)
        // list.push({ "company": "Pier Seguradora", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Pier-EI_IE2848417.13,17.htm" },)
        // list.push({ "company": "Justos", "url": "https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Justos-EI_IE5222765.13,19.htm" },)

        const tab = await new Browser().getBrowser()
        
        for (var i = 0; i < list.length; i++) {
            const page = await glassdoor.execute(list[i].url)
            data.push(page)
        }
        console.log(data)
        
        return data;
    }
}

export { extractGlassdoor } 